```{r, include = F}
# Reading Raw Data and Subsetting
if (!sum(1,1) == 2) {
# Storing Data in R
firstset<-pppub20

# Subsetting desired variables
firstset<-firstset[(c("PERIDNUM", "A_HGA", "A_SEX", "PTOT_R", "PEARNVAL", "HEA", "PERIDNUM", "A_AGE", "PEMLR"))]

# Renaming Variables
colnames(firstset) <- c("IDNUM", "H_ED", "SEX", "TOT_IN", "PEARNVAL", "HEA", "IDNUM_MATCHER", "AGE", "EMPLR")

# In order to merge with another dataset, we need a common grouping to match observations to, like state. Although state is not present in this dataset, it is present in another dataset pertaining to the same study, reporting on variables pertaining to household. The two sets report the same first 20 digits of the ID number, differing in the last two. The state variable may be taken from the household set, and matched to this set, which reports on the individual level. 
# i.e.
# H_IDNUM =  00000479261031911011
# PERIDNUM = 0000047926103191101101

# Storing the household set in R
secondset<-hhpub20

# Pulling desired variables from the household set
secondset<-secondset[(c("H_IDNUM","GESTFIPS"))]

# Renaming Variables
colnames(secondset) <- c("IDNUM","STATE")

# Abbreviating the first set's ID:
firstset$IDNUM_MATCHER<-substring(firstset$IDNUM_MATCHER, 1, nchar(firstset$IDNUM_MATCHER)-2)

# Merging firstset with secondset
CensusData<-merge(firstset, secondset, by.x = "IDNUM_MATCHER", by.y = "IDNUM")

# Exporting as a .csv file for upload to GitHub
write.csv(CensusData, "CensusData.csv", row.names = FALSE)} else {
  cat("Chunk skipped; data will be loaded into environment via GitHub in the following chunk")
}
```

```{r, include = F}
# Accessing Compiled and Wrangled Data via GitHub
CensusData<-read.csv("https://raw.githubusercontent.com/kimberlyyliuu/STAT3220Project/main/CensusData.csv",header=T)
```

```{r, echo=FALSE, warning=FALSE,results=FALSE}
# Package Installation
# Tidyverse 
if (!requireNamespace("tidyverse", quietly = T)) install.packages("tidyverse")
library(tidyverse)
if (!requireNamespace("readr", quietly = T)) install.packages("readr")
library(readr)
```




```{r}
# Constructing the a dataset reporting unemployment rates by state in 2020 from the BLS website
StatesbyFIPS<- c(1,2,4,5,6,8,9,10,11,12,13,15,16,17,18,seq(19,42,by=1),seq(44,51,by=1), 53,54,55,56)
UNEMP_RATE<-c(6.4,8.3,7.8,6.2,10.1,6.8,7.9,7.5,7.9,8.1,6.5,11.7,5.5,9.3,7.3,5.2,5.8,6.5,8.6,5.1,6.5,9.4,10.0,6.3,8.0,6.1,5.8,4.3,13.5,6.7,9.4,7.9,9.8,7.2,5.0,8.2,6.3,7.6,8.9,9.2,6.0,4.2,7.5,7.7,4.8,5.7,6.5,8.5,8.2,6.4,5.9)

# Merge the two vectors
UnemploymentRates<-data.frame(StatesbyFIPS, UNEMP_RATE)

#Merge the new dataset, UnemploymentRates, with the CensusData
compiledData<-merge(CensusData, UnemploymentRates, by.x= "STATE", by.y = "StatesbyFIPS")

#Remove unemployed people:
compiledData<-compiledData |>
  filter(1 <= EMPLR)

compiledData<-compiledData |>
  filter(4 >= EMPLR)
#Remove people under 18
compiledData <- compiledData |>
  filter(AGE >= 18)
```

Redefining Observations to be the State: 
```{r}
finalData <- compiledData |>
  group_by(STATE) |>
  summarize(across(3:10, mean, na.rm = T))
```

Reading in finalData to environment
```{r}
finalData <- read.csv("https://raw.githubusercontent.com/kimberlyyliuu/STAT3220Project/main/finalData", header = T)
```

Urban population data percents by state (see references for source): 
```{r}
UrbanPopData<-read.csv("https://raw.githubusercontent.com/kimberlyyliuu/STAT3220Project/main/UrbanPopData.csv",header=T)

# Merge with set
incompleteData<-merge(finalData, UrbanPopData, by.x="STATE")
```

Tax rates by state (see references for source): 
```{r}
TaxData<-read.csv("https://raw.githubusercontent.com/kimberlyyliuu/STAT3220Project/main/TaxData.csv",header=T)
TaxData<-TaxData[,1:3]

# Merge with set, including State names for ease of interpretation
completeData<-merge(finalData,TaxData,by.x="STATE", by.y="FIPS")
completeData<-completeData[, c("State", setdiff(names(completeData), "State"))]
#Restoring Qualitative Variables from Numeric Averages
incomeData$H_ED <- cut(incomeData$H_ED,
                            breaks = c(39, 40, 41, 42, 43),
                            labels = c("Some College but No Degree",
                                       "Vocational Associate's",
                                       "Academic Associate's",
                                       "Bachelor's"))

incomeData$HEA<-cut(incomeData$HEA,
                              breaks= c(0,1,2,3,4,5),
                              labels= c("Excellent Health",
                                        "Very Good Health",
                                        "Good Health",
                                        "Fair Health",
                                        "Poor Health"))
incomeData$SEX<-cut(incomeData$SEX,
                             breaks=c(0,1.5,2),
                             labels=c("Male","Female"))
#Renaming for simplicity
colnames(incomeData)[1]<-"STATEFIPS"

incomeData<-incomeData[,-9]

incomeData$TOT_IN<-cut(incomeData$TOT_IN,
                       breaks=c(seq(16.5,29.5,by=1)),
                       labels=c("$40,000 to $42,499",
                                "$42,500 to $44,999",
                                "$45,000 to $47,499",
                                "$47,500 to $49,999",
                                "$50,000 to $52,499",
                                "$52,500 to $54,999",
                                "$55,000 to $57,499",
                                "$57,500 to $59,999",
                                "$60,000 to $62,499",
                                "$62,500 to $64,999",
                                "$65,000 to $67,499",
                                "$67,500 to $69,999",
                                "$70,000 to $72,499"))


#Export
write.csv(completeData, "completeData", row.names = F)
```

Read in Final Version of Data from GitHub
```{r}
incomeData<-read.csv("https://raw.githubusercontent.com/kimberlyyliuu/STAT3220Project/main/completeData")
```